//+------------------------------------------------------------------+
//|                                              TEST_PROTOCOL.mq5   |
//|                            FlashEASuite V2 - Protocol Test       |
//|                    Test DeserializePolicyMessage with Grid       |
//+------------------------------------------------------------------+
#property copyright "Dr. Suksaeng Kukanok"
#property version   "2.00"
#property script_show_inputs

// Include protocol (must use EXTENDED versions)
#include "../Include/Network/Protocol.mqh"

//+------------------------------------------------------------------+
//| Script program start function                                    |
//+------------------------------------------------------------------+
void OnStart()
{
   Print("════════════════════════════════════════════════════════════════");
   Print("FlashEASuite V2 - Protocol Test (Extended Grid Fields)");
   Print("════════════════════════════════════════════════════════════════");
   Print("");
   
   // Test data from Python (PASTE FROM PYTHON OUTPUT)
   // This should be generated by running TEST_PROTOCOL.py
   uchar test_data[] = {
      // PASTE HEX DATA HERE AFTER RUNNING Python script
      // Example format:
      // 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x06, ...
   };
   
   // If test_data is empty, create manual test data
   if(ArraySize(test_data) == 0)
   {
      Print("⚠️  WARNING: test_data is empty!");
      Print("   Run TEST_PROTOCOL.py first, then paste hex output here");
      Print("");
      Print("Creating minimal test data manually...");
      
      // Create minimal valid message
      CreateMinimalTestData(test_data);
   }
   
   Print("Test Data Size: ", ArraySize(test_data), " bytes");
   Print("");
   
   // Deserialize
   PolicyMessage policy;
   
   Print("Deserializing message...");
   if(!CProtocol::DeserializePolicyMessage(test_data, policy))
   {
      Print("❌ DESERIALIZATION FAILED!");
      Print("   Check that Definitions.mqh and Serialization.mqh are EXTENDED versions");
      return;
   }
   
   Print("✅ Deserialization SUCCESS!");
   Print("");
   
   // Display all fields
   Print("═══ ORIGINAL FIELDS ═══");
   Print("Symbol:           ", policy.symbol);
   Print("Action:           ", policy.action, " (0=HOLD, 1=BUY, 2=SELL)");
   Print("Confidence:       ", DoubleToString(policy.confidence, 6));
   Print("Entry Price:      ", DoubleToString(policy.entry_price, 5));
   Print("Stop Loss:        ", DoubleToString(policy.stop_loss, 5));
   Print("Take Profit:      ", DoubleToString(policy.take_profit, 5));
   Print("Position Size:    ", DoubleToString(policy.position_size, 2));
   Print("Timestamp:        ", policy.timestamp_ms);
   Print("Model Version:    ", policy.model_version);
   Print("");
   
   Print("═══ GRID EXTENDED FIELDS ═══");
   Print("Risk Multiplier:  ", DoubleToString(policy.risk_multiplier, 6));
   Print("Is In Cooldown:   ", policy.is_in_cooldown ? "TRUE (paused)" : "FALSE (active)");
   Print("");
   Print("CSM Data:");
   Print("  USD:            ", DoubleToString(policy.csm_usd, 2));
   Print("  EUR:            ", DoubleToString(policy.csm_eur, 2));
   Print("  GBP:            ", DoubleToString(policy.csm_gbp, 2));
   Print("  JPY:            ", DoubleToString(policy.csm_jpy, 2));
   Print("  AUD:            ", DoubleToString(policy.csm_aud, 2));
   Print("  CAD:            ", DoubleToString(policy.csm_cad, 2));
   Print("  CHF:            ", DoubleToString(policy.csm_chf, 2));
   Print("  NZD:            ", DoubleToString(policy.csm_nzd, 2));
   Print("");
   Print("Grid Direction:   ", policy.grid_direction, " ", 
         policy.grid_direction == 0 ? "(NONE)" : 
         policy.grid_direction == 1 ? "(BUY)" : 
         policy.grid_direction == 2 ? "(SELL)" : "(UNKNOWN)");
   Print("");
   
   // Verification
   Print("═══ VERIFICATION ═══");
   bool all_ok = true;
   
   // Expected values (match Python test)
   string expected_symbol = "XAUUSD";
   int expected_action = 1;
   double expected_confidence = 0.85;
   double expected_risk_mult = 0.8;
   bool expected_cooldown = true;
   double expected_csm_usd = 5.2;
   int expected_grid_dir = 1;
   
   // Check each field
   if(policy.symbol != expected_symbol)
   {
      Print("❌ Symbol mismatch: ", policy.symbol, " != ", expected_symbol);
      all_ok = false;
   }
   else
   {
      Print("✅ Symbol: ", policy.symbol);
   }
   
   if(policy.action != expected_action)
   {
      Print("❌ Action mismatch: ", policy.action, " != ", expected_action);
      all_ok = false;
   }
   else
   {
      Print("✅ Action: ", policy.action);
   }
   
   if(MathAbs(policy.confidence - expected_confidence) > 0.001)
   {
      Print("❌ Confidence mismatch: ", policy.confidence, " != ", expected_confidence);
      all_ok = false;
   }
   else
   {
      Print("✅ Confidence: ", DoubleToString(policy.confidence, 6));
   }
   
   if(MathAbs(policy.risk_multiplier - expected_risk_mult) > 0.001)
   {
      Print("❌ Risk Multiplier mismatch: ", policy.risk_multiplier, " != ", expected_risk_mult);
      all_ok = false;
   }
   else
   {
      Print("✅ Risk Multiplier: ", DoubleToString(policy.risk_multiplier, 6));
   }
   
   if(policy.is_in_cooldown != expected_cooldown)
   {
      Print("❌ Cooldown mismatch: ", policy.is_in_cooldown, " != ", expected_cooldown);
      all_ok = false;
   }
   else
   {
      Print("✅ Is In Cooldown: ", policy.is_in_cooldown ? "TRUE" : "FALSE");
   }
   
   if(MathAbs(policy.csm_usd - expected_csm_usd) > 0.001)
   {
      Print("❌ CSM USD mismatch: ", policy.csm_usd, " != ", expected_csm_usd);
      all_ok = false;
   }
   else
   {
      Print("✅ CSM USD: ", DoubleToString(policy.csm_usd, 2));
   }
   
   if(policy.grid_direction != expected_grid_dir)
   {
      Print("❌ Grid Direction mismatch: ", policy.grid_direction, " != ", expected_grid_dir);
      all_ok = false;
   }
   else
   {
      Print("✅ Grid Direction: ", policy.grid_direction);
   }
   
   Print("");
   
   if(all_ok)
   {
      Print("════════════════════════════════════════════════════════════════");
      Print("✅✅✅ ALL TESTS PASSED! ✅✅✅");
      Print("════════════════════════════════════════════════════════════════");
      Print("");
      Print("Protocol is working correctly!");
      Print("Ready to proceed to Phase 2 (Grid Integration)");
   }
   else
   {
      Print("════════════════════════════════════════════════════════════════");
      Print("❌ SOME TESTS FAILED!");
      Print("════════════════════════════════════════════════════════════════");
      Print("");
      Print("Check:");
      Print("1. Definitions.mqh has all 11 new fields");
      Print("2. Serialization.mqh serialize/deserialize updated");
      Print("3. Python policy.py pack_custom_protocol() updated");
      Print("4. Field order matches between Python and MQL5");
   }
}

//+------------------------------------------------------------------+
//| Create minimal test data for testing without Python             |
//+------------------------------------------------------------------+
void CreateMinimalTestData(uchar &data[])
{
   ArrayResize(data, 0);
   
   // Create a minimal PolicyMessage
   PolicyMessage msg;
   msg.symbol = "XAUUSD";
   msg.action = 1;
   msg.confidence = 0.85;
   msg.entry_price = 2650.50;
   msg.stop_loss = 2640.00;
   msg.take_profit = 2670.00;
   msg.position_size = 0.01;
   msg.timestamp_ms = 1735368000000;
   msg.model_version = "GRID_V2_TEST";
   
   // Grid fields
   msg.risk_multiplier = 0.8;
   msg.is_in_cooldown = true;
   msg.csm_usd = 5.2;
   msg.csm_eur = 4.8;
   msg.csm_gbp = 3.5;
   msg.csm_jpy = -2.1;
   msg.csm_aud = 1.2;
   msg.csm_cad = 0.5;
   msg.csm_chf = -1.0;
   msg.csm_nzd = 2.3;
   msg.grid_direction = 1;
   
   // Serialize it
   if(!CProtocol::SerializePolicyMessage(msg, data))
   {
      Print("❌ Failed to create test data");
      ArrayResize(data, 0);
   }
   else
   {
      Print("✅ Created test data: ", ArraySize(data), " bytes");
   }
}
//+------------------------------------------------------------------+
